engines:
  golint:
    enabled: true
    exclude_patterns:
    - "**/"                # exclude all
    - "!./cmd/"            # unexclude just the ones we want to lint
    - "!./pkg/"
    - "!./templates/"

  gofmt:
    enabled: true

  shellcheck:
    enabled: true

