name: Release tests

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0-alpha.3

      - uses: azure/setup-helm@v1

      - name: Setup Helm Repos
        run: helm repo add stable https://kubernetes-charts.storage.googleapis.com/ && helm repo update

      - name: Setup Authenticator Test Case
        working-directory: ./test
        run: ./up.sh

      - name: Run Tests
        working-directory: ./test
        run: RELEASE_TESTS=1 go test -v -count=1 ./...
