name: Unit Tests
on:
  # Only run this on pushes to master
  push:
    branches:
    - master

  # And when PRs operations are done
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set BRANCH_NAME
      run: echo "::set-env name=GIT_BRANCH::${GITHUB_REF#refs/heads/}"

    - name: Prepare CC for reporting data
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: go test -v -coverprofile=c.out -count=1 ./...

    - name: Submit CC Report
      run: |
        # cc-test-reporter doesn't work OOTB w/ Go modules
        # https://github.com/codeclimate/test-reporter/issues/378
        export PREFIX="$(go list -m)"
        ./cc-test-reporter after-build -p "$PREFIX"
